### ISSUE TITLE
Updating Newsletters Page

### ISSUE THREAD

**Issue by JasmineZhangxyz** [Ethical-Principles-in-AI/Ethical-Principles-in-AI.github.io#11]
Can you please add newsletters 3-5 onto the "Newsletters" Page? Thank you!

Links:
3: can't find the link, so feel free to leave out this one
4: https://us5.campaign-archive.com/?e=__test_email__&u=cd0bced23d8762ad5ea829c18&id=307ce072cf
5: https://us5.campaign-archive.com/?e=__test_email__&u=cd0bced23d8762ad5ea829c18&id=af7d30a378

**Comment by chasemcdo** [comment]
https://ethical-principles-in-ai.github.io/news
