### ISSUE TITLE
Add Feb 15th Speaker Series to "Upcoming Events"

### ISSUE THREAD

**Issue by JasmineZhangxyz** [Ethical-Principles-in-AI/Ethical-Principles-in-AI.github.io#12]
Can you please add details about the Speaker Series happening on Feb 15th onto our website?

Graphic: Anya sent in Discord under #marketing
Title: Speaker Series: Decolonize AI
Date: February 15th, 6-7pm
Registration Link: https://utoronto.zoom.us/meeting/register/tZcodO6rrDIjHN1GZLi9nPag9Qlk8fishISJ
Event Abstract: https://docs.google.com/document/d/1vyfVuZtfjXSwTcSzRn76hrdcmaFSKu4jBU-c6koig2Y/edit

Thank you!

**Comment by chasemcdo** [comment]
https://ethical-principles-in-ai.github.io/Decolonize_AI
