### ISSUE TITLE
Home page "join us" link

### ISSUE THREAD

**Issue by emily0622** [Ethical-Principles-in-AI/Ethical-Principles-in-AI.github.io#3]
returns a 404 error page

**Comment by JasmineZhangxyz** [comment]
[Minor concern] The "join us" link works for me but doesn't automatically lead to the top of the "join us" page. Depending on where you've scrolled to on the home page, it'll lead you to that place on the join us page. 

For example, if I scroll to the bottom of the home page before clicking the "join us" link, then I get taken to the bottom of the "join us" page.

**Comment by chasemcdo** [comment]
The join us links are functional on my end though I do get the jump to the bottom of the page. I'll see if I can adjust it to come to the top of the page.

**Comment by chasemcdo** [comment]
Updated the site to remedy the position issue. Now you should come to the top of the page when switching between them.

**Comment by chasemcdo** [comment]
I'll leave this issue open since that wasn't the original issue though
