### ISSUE TITLE
Might not need calendar for "Events" Page

### ISSUE THREAD

**Issue by JasmineZhangxyz** [Ethical-Principles-in-AI/Ethical-Principles-in-AI.github.io#8]
Not a technical issue, just a design preference!

I don't think we have enough events going on at a time to need a calendar. Having the blank calendar show up before the description of upcoming events means that people will have to scroll past it. Removing the calendar could help website visitors see the upcoming events easier.

(Also, the blank or nearly blank calendar can leave a bad impression).

**Comment by chasemcdo** [comment]
Sounds good. Put it there since we had it on the main site, but definitely agree that the nearly blank calendar doesn't leave a great impression.

**Comment by chasemcdo** [comment]
I commented out the code for the calendar, so we can easily add it back in the future if we so desire.
